package net.devmanuals.model;

// Generated Aug 31, 2013 2:18:56 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Object generated by hbm2java
 */
@Entity
@Table(name = "object")
public class Object implements java.io.Serializable {

	private Integer id;
	private String url;
	private String type;
	private Set<Statement> statements = new HashSet<Statement>(0);

	public Object() {
	}

	public Object(String url, String type) {
		this.url = url;
		this.type = type;
	}

	public Object(String url, String type, Set<Statement> statements) {
		this.url = url;
		this.type = type;
		this.statements = statements;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "url", nullable = false, length = 100)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "type", nullable = false, length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "object")
	public Set<Statement> getStatements() {
		return this.statements;
	}

	public void setStatements(Set<Statement> statements) {
		this.statements = statements;
	}

}
