package net.devmanuals.model;

// Generated Aug 31, 2013 2:18:56 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Statement generated by hbm2java
 */
@Entity
@Table(name = "statement")
public class Statement implements java.io.Serializable {

	private Integer id;
	private Verb verb;
	private Users users;
	private Object object;
	private Date store;

	public Statement() {
	}

	public Statement(Verb verb, Users users, Object object, Date store) {
		this.verb = verb;
		this.users = users;
		this.object = object;
		this.store = store;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "verb_id", nullable = false)
	public Verb getVerb() {
		return this.verb;
	}

	public void setVerb(Verb verb) {
		this.verb = verb;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "object_id", nullable = false)
	public Object getObject() {
		return this.object;
	}

	public void setObject(Object object) {
		this.object = object;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "store", nullable = false, length = 19)
	public Date getStore() {
		return this.store;
	}

	public void setStore(Date store) {
		this.store = store;
	}

}
