package net.devmanuals.model;

// Generated Aug 31, 2013 2:18:56 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Verb generated by hbm2java
 */
@Entity
@Table(name = "verb")
public class Verb implements java.io.Serializable {

	private Integer id;
	private String urlId;
	private String type;
	private Set<Statement> statements = new HashSet<Statement>(0);

	public Verb() {
	}

	public Verb(String urlId, String type) {
		this.urlId = urlId;
		this.type = type;
	}

	public Verb(String urlId, String type, Set<Statement> statements) {
		this.urlId = urlId;
		this.type = type;
		this.statements = statements;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "url_id", nullable = false, length = 100)
	public String getUrlId() {
		return this.urlId;
	}

	public void setUrlId(String urlId) {
		this.urlId = urlId;
	}

	@Column(name = "type", nullable = false, length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "verb")
	public Set<Statement> getStatements() {
		return this.statements;
	}

	public void setStatements(Set<Statement> statements) {
		this.statements = statements;
	}

}
